/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.Test;
import org.testng.AssertJUnit;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        AssertJUnit.assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
